# Generated by Django 5.2.8 on 2026-03-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_brand_id_alter_fragrance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_size_ml', models.PositiveIntegerField(default=2)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pack_items', to='catalog.fragrance')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='samples.weeklypack')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pack', 'fragrance'), name='unique_pack_fragrance')],
            },
        ),
    ]
